#' Save TensorFlow Model
#'
#' Saves a TensorFlow model with the goal of deploying and reusing across systems.
#'
#' @param model A TensorFlow model. For instance, as generated by \code{linear_regressor()}.
#' @param path The destination path where the model will be saved.
#'
#' @family save
#' @export
export_savedmodel <- function(sess, path) {
  versioned_path <- file.path(path, "1")

  builder <- tf$saved_model$builder$SavedModelBuilder(versioned_path)
  builder$save()

  variables_path <- file.path(versioned_path, "variables")

  if (!dir.exists(variables_path)) dir.create(variables_path, recursive = TRUE)
  variables_files <- file.path(variables_path, "variables")

  saver <- tf$train$Saver()
  saver$save(sess, variables_files)
}
